[[redirects]]
from = "/api/*"
to = "https://www.swiggy.com/:splat"
status = 200
force = true
[[redirects]]
from ='/*'
to ='/index.html'
status = 200
[build]
command = "npm install --legacy-peer-deps && npm run build"
